
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class company extends javax.swing.JFrame {
    DefaultTableModel dtm;
    /**
     * Creates new form company
     */
    Connection con;
    public company() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        dtm = new DefaultTableModel();
        dtm.addColumn("Company Name");
        dtm.addColumn("Company Number");
        dtm.addColumn("Company Address");
        dtm.addColumn("Drug Name");
        dtm.addColumn("Drug Price");
        dtm.addColumn("Drug Amount");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/med_care", "root", "root");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_pnl = new javax.swing.JPanel();
        img_logo = new javax.swing.JLabel();
        logo_lbl = new javax.swing.JLabel();
        dash_pnl = new javax.swing.JPanel();
        company_btn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        indicator2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        personal_btn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        indicator3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        check_btn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        indicator5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        profit_btn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        indicator4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        home_btn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        indicator1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        companyname_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        add_deal = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        companyphone_input = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        companyaddress_input = new javax.swing.JTextField();
        delet_data = new javax.swing.JButton();
        update_data = new javax.swing.JButton();
        med_name_lbl = new javax.swing.JLabel();
        med_name_input = new javax.swing.JTextField();
        med_amount_lbl = new javax.swing.JLabel();
        med_amount_input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        company_table = new javax.swing.JTable();
        med_amount_lbl1 = new javax.swing.JLabel();
        med_price_input = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo_pnl.setBackground(new java.awt.Color(0, 204, 183));

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/capsules.png"))); // NOI18N

        logo_lbl.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        logo_lbl.setForeground(new java.awt.Color(255, 255, 255));
        logo_lbl.setText("Med Care");

        javax.swing.GroupLayout logo_pnlLayout = new javax.swing.GroupLayout(logo_pnl);
        logo_pnl.setLayout(logo_pnlLayout);
        logo_pnlLayout.setHorizontalGroup(
            logo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(726, 726, 726))
        );
        logo_pnlLayout.setVerticalGroup(
            logo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_pnlLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(logo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_logo)
                    .addComponent(logo_lbl))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        dash_pnl.setBackground(new java.awt.Color(233, 233, 233));

        company_btn.setBackground(new java.awt.Color(0, 204, 183));
        company_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setBackground(new java.awt.Color(233, 233, 233));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Companies");

        indicator2.setBackground(new java.awt.Color(2, 152, 137));
        indicator2.setOpaque(false);

        javax.swing.GroupLayout indicator2Layout = new javax.swing.GroupLayout(indicator2);
        indicator2.setLayout(indicator2Layout);
        indicator2Layout.setHorizontalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        indicator2Layout.setVerticalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/company.png"))); // NOI18N

        javax.swing.GroupLayout company_btnLayout = new javax.swing.GroupLayout(company_btn);
        company_btn.setLayout(company_btnLayout);
        company_btnLayout.setHorizontalGroup(
            company_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(company_btnLayout.createSequentialGroup()
                .addComponent(indicator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        company_btnLayout.setVerticalGroup(
            company_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(company_btnLayout.createSequentialGroup()
                .addGroup(company_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(company_btnLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(company_btnLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        personal_btn.setBackground(new java.awt.Color(233, 233, 233));
        personal_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personal_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personal_btnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Personnel");

        indicator3.setBackground(new java.awt.Color(2, 152, 137));
        indicator3.setOpaque(false);

        javax.swing.GroupLayout indicator3Layout = new javax.swing.GroupLayout(indicator3);
        indicator3.setLayout(indicator3Layout);
        indicator3Layout.setHorizontalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        indicator3Layout.setVerticalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/staff.png"))); // NOI18N

        javax.swing.GroupLayout personal_btnLayout = new javax.swing.GroupLayout(personal_btn);
        personal_btn.setLayout(personal_btnLayout);
        personal_btnLayout.setHorizontalGroup(
            personal_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_btnLayout.createSequentialGroup()
                .addComponent(indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personal_btnLayout.setVerticalGroup(
            personal_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_btnLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(personal_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        check_btn.setBackground(new java.awt.Color(233, 233, 233));
        check_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_btnMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Check");

        indicator5.setBackground(new java.awt.Color(2, 152, 137));
        indicator5.setOpaque(false);

        javax.swing.GroupLayout indicator5Layout = new javax.swing.GroupLayout(indicator5);
        indicator5.setLayout(indicator5Layout);
        indicator5Layout.setHorizontalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        indicator5Layout.setVerticalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N

        javax.swing.GroupLayout check_btnLayout = new javax.swing.GroupLayout(check_btn);
        check_btn.setLayout(check_btnLayout);
        check_btnLayout.setHorizontalGroup(
            check_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, check_btnLayout.createSequentialGroup()
                .addComponent(indicator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        check_btnLayout.setVerticalGroup(
            check_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(check_btnLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(check_btnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profit_btn.setBackground(new java.awt.Color(233, 233, 233));
        profit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profit_btnMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Profit");

        indicator4.setBackground(new java.awt.Color(2, 152, 137));
        indicator4.setOpaque(false);

        javax.swing.GroupLayout indicator4Layout = new javax.swing.GroupLayout(indicator4);
        indicator4.setLayout(indicator4Layout);
        indicator4Layout.setHorizontalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        indicator4Layout.setVerticalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand.png"))); // NOI18N

        javax.swing.GroupLayout profit_btnLayout = new javax.swing.GroupLayout(profit_btn);
        profit_btn.setLayout(profit_btnLayout);
        profit_btnLayout.setHorizontalGroup(
            profit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profit_btnLayout.createSequentialGroup()
                .addComponent(indicator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profit_btnLayout.setVerticalGroup(
            profit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profit_btnLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(profit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profit_btnLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)))
                .addGap(26, 26, 26))
        );

        home_btn.setBackground(new java.awt.Color(233, 233, 233));
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_btnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Home");

        indicator1.setBackground(new java.awt.Color(2, 152, 137));
        indicator1.setOpaque(false);

        javax.swing.GroupLayout indicator1Layout = new javax.swing.GroupLayout(indicator1);
        indicator1.setLayout(indicator1Layout);
        indicator1Layout.setHorizontalGroup(
            indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        indicator1Layout.setVerticalGroup(
            indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/medical-history.png"))); // NOI18N

        javax.swing.GroupLayout home_btnLayout = new javax.swing.GroupLayout(home_btn);
        home_btn.setLayout(home_btnLayout);
        home_btnLayout.setHorizontalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                .addComponent(indicator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        home_btnLayout.setVerticalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout dash_pnlLayout = new javax.swing.GroupLayout(dash_pnl);
        dash_pnl.setLayout(dash_pnlLayout);
        dash_pnlLayout.setHorizontalGroup(
            dash_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personal_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(check_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(company_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(home_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dash_pnlLayout.setVerticalGroup(
            dash_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash_pnlLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(company_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(personal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(profit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Company Phone : ");

        companyname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyname_inputActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add_deal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add_deal.setText("Add Deal");
        add_deal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_dealActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Company Name : ");

        companyphone_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyphone_inputActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Company Address : ");

        companyaddress_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyaddress_inputActionPerformed(evt);
            }
        });

        delet_data.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delet_data.setText("Delete");
        delet_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_dataActionPerformed(evt);
            }
        });

        update_data.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        update_data.setText("Update");
        update_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_dataActionPerformed(evt);
            }
        });

        med_name_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        med_name_lbl.setText("Medicine Name: ");

        med_name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_name_inputActionPerformed(evt);
            }
        });

        med_amount_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        med_amount_lbl.setText("Medicine Amount : ");

        med_amount_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_amount_inputActionPerformed(evt);
            }
        });

        company_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Address", "Medicine Name", "Medicine amount"
            }
        ));
        company_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                company_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(company_table);

        med_amount_lbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        med_amount_lbl1.setText("Medicine Price : ");

        med_price_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_price_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(dash_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(add_deal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(companyphone_input, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(companyaddress_input, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(companyname_input, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11))))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(delet_data, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(update_data, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(med_name_lbl)
                                    .addComponent(med_amount_lbl)
                                    .addComponent(med_amount_lbl1))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(med_amount_input, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(med_price_input, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(med_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1723, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(companyname_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(med_name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(med_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(med_amount_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med_amount_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyphone_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(med_amount_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med_price_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyaddress_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_deal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delet_data, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_data, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
                    .addComponent(dash_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personal_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personal_btnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new personnel().setVisible(true);
    }//GEN-LAST:event_personal_btnMouseClicked

    private void check_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_btnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new check().setVisible(true);
    }//GEN-LAST:event_check_btnMouseClicked

    private void profit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profit_btnMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_profit_btnMouseClicked

    private void companyname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyname_inputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_dealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_dealActionPerformed
        // TODO add your handling code here: 
//  ==============================>>>> why      if(total_amount_deals_input.getText().equals(true)){
//            JOptionPane.showMessageDialog(this,"Total Ammount nt input by UU its option show in (search botton)");
//        }
        if(companyname_input.getText().equals("") || companyphone_input.getText().equals("") || companyaddress_input.getText().equals("") || med_name_input.getText().equals("") || med_amount_input.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please, Add all data!");
        }
        else{
            String data[] = { companyname_input.getText(),companyphone_input.getText(), companyaddress_input.getText(),med_name_input.getText(),med_amount_input.getText()};
            DefaultTableModel tblModel = (DefaultTableModel)company_table.getModel();
            tblModel.addRow(data);
            try {
                PreparedStatement check = con.prepareStatement("select m_name from manufactors where m_name=?");
                check.setString(1, companyname_input.getText());
                ResultSet rs = check.executeQuery();
                if(!rs.next())
                {
                    PreparedStatement stm = con.prepareStatement("insert into manufactors (m_name,m_number, m_address) values (?, ?, ?)");
                    stm.setString(1, companyname_input.getText());
                    stm.setInt(2, (int) Double.parseDouble(companyphone_input.getText()));
                    stm.setString(3, companyaddress_input.getText());
                    stm.executeUpdate();
                }
                PreparedStatement stm2 = con.prepareStatement("insert into drugs (drug_name, amount, m_name, drug_price) values (?, ?, ?, ?)");
                stm2.setString(3, companyname_input.getText());
                stm2.setString(1, med_name_input.getText());
                stm2.setInt(2, (int) Double.parseDouble(med_amount_input.getText()));
                stm2.setInt(4, (int) Double.parseDouble(med_price_input.getText()));
                stm2.executeUpdate();
                JOptionPane.showMessageDialog(this,"Added Successfully!");
                fillTable();
            } catch (SQLException ex) {
                Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
            companyname_input.setText("");
            companyphone_input.setText("");
            companyaddress_input.setText("");
            med_name_input.setText("");
            med_amount_input.setText("");
            }
    }//GEN-LAST:event_add_dealActionPerformed
    private void fillTable() {
        try {
            dtm.setRowCount(0);
            PreparedStatement stm = con.prepareStatement("select drugs.m_name, manufactors.m_number, manufactors.m_address,drugs.drug_name, drugs.drug_price, drugs.amount from manufactors, drugs where drugs.m_name = manufactors.m_name");
            ResultSet rs = stm.executeQuery();
            while(rs.next())
            {
                dtm.addRow(new Object[]{rs.getString(1),rs.getInt(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});  
            }
            company_table.setModel(dtm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    private void companyphone_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyphone_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyphone_inputActionPerformed

    private void companyaddress_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyaddress_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyaddress_inputActionPerformed

    private void delet_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_dataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)company_table.getModel();
        if(company_table.getSelectedRowCount() == 1){
            //if single row selected
            try {
                String address = tblModel.getValueAt(company_table.getSelectedRow(),2).toString();
                int num = (int) tblModel.getValueAt(company_table.getSelectedRow(),1);
                PreparedStatement stm = con.prepareStatement("delete manufactors, drugs from manufactors inner join drugs on drugs.m_name = manufactors.m_name where manufactors.m_number=? and manufactors.m_address=?");
                stm.setInt(1, num);
                stm.setString(2, address);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data Deleted Successfully!");
                fillTable();
            } catch (SQLException ex) {
                Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
            companyname_input.setText("");
            companyphone_input.setText("");
            companyaddress_input.setText("");
            med_name_input.setText("");
            med_amount_input.setText("");
        }
        else{
            //if row empty
            if(company_table.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                //if row nt selected || multi roe selected
                JOptionPane.showMessageDialog(this,"Please, Select Single Row For Update");
            }
        }
    }//GEN-LAST:event_delet_dataActionPerformed

    private void update_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_dataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)company_table.getModel();
        if(company_table.getSelectedRowCount() == 1){
            try {
                // if row selected
                String name = tblModel.getValueAt(company_table.getSelectedRow(),3).toString();
                int num = (int) tblModel.getValueAt(company_table.getSelectedRow(),1);
                PreparedStatement stm = con.prepareStatement("update manufactors set m_number=? , m_address=? where m_number=?");
                stm.setInt(1, (int) Double.parseDouble(companyphone_input.getText()));
                stm.setString(2, companyaddress_input.getText());
                stm.setInt(3, num);
                stm.executeUpdate();
                PreparedStatement stm2 = con.prepareStatement("update drugs set drug_name=?, amount=?, drug_price=? where drug_name=?");
                stm2.setString(1, med_name_input.getText());
                stm2.setInt(2, (int) Double.parseDouble(med_amount_input.getText()));
                stm2.setInt(3, (int) Double.parseDouble(med_price_input.getText()));
                stm2.setString(4, name);
                stm2.executeUpdate();
                fillTable();
                companyname_input.setText("");
                companyphone_input.setText("");
                companyaddress_input.setText("");
                med_name_input.setText("");
                med_amount_input.setText("");
                med_price_input.setText(""); 
                JOptionPane.showMessageDialog(this,"Data Updated Successfully!");
            } catch (SQLException ex) {
                Logger.getLogger(company.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            if(company_table.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                //if row nt selected || multi roe selected
                JOptionPane.showMessageDialog(this,"Please, Select Single Row For Update");
            }
        }
    }//GEN-LAST:event_update_dataActionPerformed

    private void home_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new DashboardForm().setVisible(true);
    }//GEN-LAST:event_home_btnMouseClicked

    private void med_name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_name_inputActionPerformed

    private void med_amount_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_amount_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_amount_inputActionPerformed

    private void company_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_company_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)company_table.getModel();
        companyname_input.setText(tblModel.getValueAt(company_table.getSelectedRow(),0).toString());
        companyphone_input.setText(tblModel.getValueAt(company_table.getSelectedRow(),1).toString());
        companyaddress_input.setText(tblModel.getValueAt(company_table.getSelectedRow(),2).toString());
        med_name_input.setText(tblModel.getValueAt(company_table.getSelectedRow(),3).toString());
        med_price_input.setText(tblModel.getValueAt(company_table.getSelectedRow(),4).toString());
        med_amount_input.setText(tblModel.getValueAt(company_table.getSelectedRow(),5).toString());
    }//GEN-LAST:event_company_tableMouseClicked

    private void med_price_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_price_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_price_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_deal;
    private javax.swing.JPanel check_btn;
    private javax.swing.JPanel company_btn;
    private javax.swing.JTable company_table;
    private javax.swing.JTextField companyaddress_input;
    private javax.swing.JTextField companyname_input;
    private javax.swing.JTextField companyphone_input;
    private javax.swing.JPanel dash_pnl;
    private javax.swing.JButton delet_data;
    private javax.swing.JPanel home_btn;
    private javax.swing.JLabel img_logo;
    private javax.swing.JPanel indicator1;
    private javax.swing.JPanel indicator2;
    private javax.swing.JPanel indicator3;
    private javax.swing.JPanel indicator4;
    private javax.swing.JPanel indicator5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_lbl;
    private javax.swing.JPanel logo_pnl;
    private javax.swing.JTextField med_amount_input;
    private javax.swing.JLabel med_amount_lbl;
    private javax.swing.JLabel med_amount_lbl1;
    private javax.swing.JTextField med_name_input;
    private javax.swing.JLabel med_name_lbl;
    private javax.swing.JTextField med_price_input;
    private javax.swing.JPanel personal_btn;
    private javax.swing.JPanel profit_btn;
    private javax.swing.JButton update_data;
    // End of variables declaration//GEN-END:variables
}
