
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class leave extends javax.swing.JFrame {
    String time;
    /**
     * Creates new form leave
     */
    DefaultTableModel dtm;
    Connection con;
    public leave() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        dtm = new DefaultTableModel();
        dtm.addColumn("Employee ID");
        dtm.addColumn("Employee Name");
        dtm.addColumn("Employee Number");
        dtm.addColumn("Attendence Time");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/med_care", "root", "root");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillTable();
    }
    private void fillTable() {
        try {
            dtm.setRowCount(0);
            PreparedStatement stm = con.prepareStatement("select employee_id, employee_name, employee_num, leave_t from employee");
            ResultSet rs = stm.executeQuery();
            while(rs.next())
            {
                dtm.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getString(4)});  
            }
            leave_table.setModel(dtm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emp_id_lbl = new javax.swing.JLabel();
        add_emp_id = new javax.swing.JTextField();
        emp_name_lbl = new javax.swing.JLabel();
        add_emp_name = new javax.swing.JTextField();
        deletData = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        leave_table = new javax.swing.JTable();
        updateData = new javax.swing.JToggleButton();
        addData = new javax.swing.JToggleButton();
        back_btn = new javax.swing.JLabel();
        emp_job_lbl = new javax.swing.JLabel();
        add_emp_number = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        emp_id_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emp_id_lbl.setText("Id : ");

        add_emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_emp_idActionPerformed(evt);
            }
        });

        emp_name_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emp_name_lbl.setText("Name : ");

        deletData.setBackground(new java.awt.Color(0, 204, 183));
        deletData.setText("Delet Data");
        deletData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletDataActionPerformed(evt);
            }
        });

        leave_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Job", "Time(leave)"
            }
        ));
        leave_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leave_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(leave_table);

        updateData.setBackground(new java.awt.Color(0, 204, 183));
        updateData.setText("Update Data");
        updateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataActionPerformed(evt);
            }
        });

        addData.setBackground(new java.awt.Color(0, 204, 183));
        addData.setText("Add Data");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        emp_job_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emp_job_lbl.setText("Number :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_btn)
                .addGap(429, 429, 429))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_id_lbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_job_lbl)
                            .addComponent(emp_name_lbl))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_emp_number, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(195, 195, 195)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateData, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deletData, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back_btn)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_job_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_emp_number, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_emp_idActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_add_emp_idActionPerformed

    private void deletDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletDataActionPerformed
        // TODO add your handling code here:
        // get table 
        DefaultTableModel tblModel = (DefaultTableModel)leave_table.getModel();
        // delet row
        if(leave_table.getSelectedRowCount() == 1){
            //if single row selected
            tblModel.removeRow(leave_table.getSelectedRow());
        }
        else{
            //if row empty
            if(leave_table.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                //if row nt selected || multi roe selected
                JOptionPane.showMessageDialog(this,"Plz, Select Single Row For Update");
            }
        }
        
    }//GEN-LAST:event_deletDataActionPerformed

    private void updateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)leave_table.getModel();
        if(leave_table.getSelectedRowCount() == 1){
            // if row selected
            //set to uptade value in row 
            try {
                // if row selected
                PreparedStatement stm = con.prepareStatement("update employee set employee_name=?, employee_num=?, leave_t=? where employee_id=?");
                stm.setString(1, add_emp_name.getText());
                stm.setInt(2, (int) Double.parseDouble(add_emp_number.getText()));
                stm.setInt(3, 0);
                stm.setInt(4, (int) Double.parseDouble(add_emp_id.getText()));
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data Updated Successfully!");
                fillTable();
            } catch (SQLException ex) {
                Logger.getLogger(company.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            if(leave_table.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                //if row nt selected || multi roe selected
                JOptionPane.showMessageDialog(this,"Plz, Select Single Row For Update");
            }
        }
        
    }//GEN-LAST:event_updateDataActionPerformed

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");  
         Date date = new Date();  
        if(add_emp_name.getText().equals("") || add_emp_id.getText().equals("") ||  add_emp_number.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Plz, Add all data!");
        }
        else{
            String data[] = { add_emp_id.getText(), add_emp_name.getText(), add_emp_number.getText()};
            DefaultTableModel tblModel = (DefaultTableModel)leave_table.getModel();
            try {
                PreparedStatement stm = con.prepareStatement("insert into employee (employee_name,employee_id, employee_num, attendence) values (?, ?, ?, ?)");
                stm.setString(1, add_emp_name.getText());
                stm.setInt(2, (int) Double.parseDouble(add_emp_id.getText()));
                stm.setInt(3, (int) Double.parseDouble(add_emp_number.getText()));
                stm.setInt(4, 0);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this,"Added Successfully!");
                fillTable();
                add_emp_id.setText("");
                add_emp_name.setText("");
                add_emp_number.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
            }
            fillTable();
            JOptionPane.showMessageDialog(this,"Data Added Successfully!");
            add_emp_id.setText("");
            add_emp_name.setText("");
            add_emp_number.setText("");
            }
         
    }//GEN-LAST:event_addDataActionPerformed

    private void leave_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leave_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)leave_table.getModel();

        String tblId =  tblModel.getValueAt(leave_table.getSelectedRow(),0).toString();
        String tblName =  tblModel.getValueAt(leave_table.getSelectedRow(),1).toString();
        String tblJob =  tblModel.getValueAt(leave_table.getSelectedRow(),2).toString();
        add_emp_name.setText(tblName);
        add_emp_id.setText(tblId);
        add_emp_number.setText(tblJob);
    }//GEN-LAST:event_leave_tableMouseClicked

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new personnel().setVisible(true);
    }//GEN-LAST:event_back_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addData;
    private javax.swing.JTextField add_emp_id;
    private javax.swing.JTextField add_emp_name;
    private javax.swing.JTextField add_emp_number;
    private javax.swing.JLabel back_btn;
    private javax.swing.JToggleButton deletData;
    private javax.swing.JLabel emp_id_lbl;
    private javax.swing.JLabel emp_job_lbl;
    private javax.swing.JLabel emp_name_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable leave_table;
    private javax.swing.JToggleButton updateData;
    // End of variables declaration//GEN-END:variables
}
