
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LoginFormm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFormm
     */
    String txt_username, txt_password;
    Connection con;
    public LoginFormm() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/med_care", "root", "root");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_lbl1 = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        password_input = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        username_lbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username_lbl1.setForeground(new java.awt.Color(0, 204, 183));
        username_lbl1.setText("Username :");
        getContentPane().add(username_lbl1);
        username_lbl1.setBounds(940, 410, 124, 29);

        password_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password_lbl.setForeground(new java.awt.Color(0, 204, 183));
        password_lbl.setText("Password :");
        getContentPane().add(password_lbl);
        password_lbl.setBounds(940, 510, 117, 29);
        getContentPane().add(username_input);
        username_input.setBounds(1110, 410, 260, 40);

        password_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_inputActionPerformed(evt);
            }
        });
        getContentPane().add(password_input);
        password_input.setBounds(1110, 510, 260, 40);

        login_btn.setBackground(new java.awt.Color(255, 255, 255));
        login_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        login_btn.setForeground(new java.awt.Color(0, 204, 183));
        login_btn.setText("Login");
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn);
        login_btn.setBounds(1070, 610, 110, 40);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/v870-tang-36.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 2020, 1220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_inputActionPerformed

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btnMouseClicked

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txt_username = "admin";
        txt_password = "admin";
        if (username_input.getText().equals(txt_username)  && password_input.getText().equals(txt_password)) {
            DashboardForm dash = new DashboardForm();
            dash.setVisible(true);
    }                                         
        else{
            JOptionPane.showMessageDialog(this,"Wrong username or password");
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFormm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_lbl1;
    // End of variables declaration//GEN-END:variables
}
