/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Menna
 */
public class new_member extends javax.swing.JFrame {
    DefaultTableModel dtm;
    Connection con;
    /**
     * Creates new form new_member
     */
    public new_member() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        dtm = new DefaultTableModel();
        dtm.addColumn("Employee ID");
        dtm.addColumn("Employee Name");
        dtm.addColumn("Employee Number");
        dtm.addColumn("Employee Address");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/med_care", "root", "root");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillTable();
    }
    private void fillTable() {
        try {
            dtm.setRowCount(0);
            PreparedStatement stm = con.prepareStatement("select employee_id, employee_name, employee_num, employee_address from employee");
            ResultSet rs = stm.executeQuery();
            while(rs.next())
            {
                dtm.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getString(4)});  
            }
            attend_table.setModel(dtm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        attendance_pnl = new javax.swing.JPanel();
        emp_id_lbl = new javax.swing.JLabel();
        add_emp_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        attend_table = new javax.swing.JTable();
        emp_name_lbl = new javax.swing.JLabel();
        add_emp_name = new javax.swing.JTextField();
        addData = new javax.swing.JToggleButton();
        updateData = new javax.swing.JToggleButton();
        deletData = new javax.swing.JToggleButton();
        back_btn = new javax.swing.JLabel();
        emp_job_lbl = new javax.swing.JLabel();
        add_emp_number = new javax.swing.JTextField();
        emp_job_lbl1 = new javax.swing.JLabel();
        add_emp_address = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        attendance_pnl.setBackground(new java.awt.Color(255, 255, 255));

        emp_id_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emp_id_lbl.setText("Id : ");

        add_emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_emp_idActionPerformed(evt);
            }
        });

        attend_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Job", "Time(attendance)"
            }
        ));
        attend_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attend_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(attend_table);

        emp_name_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emp_name_lbl.setText("Name : ");

        addData.setBackground(new java.awt.Color(0, 204, 183));
        addData.setText("Add Data");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        updateData.setBackground(new java.awt.Color(0, 204, 183));
        updateData.setText("Update Data");
        updateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataActionPerformed(evt);
            }
        });

        deletData.setBackground(new java.awt.Color(0, 204, 183));
        deletData.setText("Delet Data");
        deletData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletDataActionPerformed(evt);
            }
        });

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        emp_job_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emp_job_lbl.setText("Number :");

        emp_job_lbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        emp_job_lbl1.setText("Address :");

        javax.swing.GroupLayout attendance_pnlLayout = new javax.swing.GroupLayout(attendance_pnl);
        attendance_pnl.setLayout(attendance_pnlLayout);
        attendance_pnlLayout.setHorizontalGroup(
            attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
            .addGroup(attendance_pnlLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_job_lbl)
                    .addComponent(emp_name_lbl)
                    .addComponent(emp_job_lbl1)
                    .addComponent(emp_id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(attendance_pnlLayout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(add_emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendance_pnlLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(add_emp_number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(add_emp_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendance_pnlLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(add_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140)
                .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateData, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(deletData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendance_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        attendance_pnlLayout.setVerticalGroup(
            attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendance_pnlLayout.createSequentialGroup()
                .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attendance_pnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emp_id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attendance_pnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attendance_pnlLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(emp_name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_job_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attendance_pnlLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attendance_pnlLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(add_emp_number, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendance_pnlLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(deletData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attendance_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_job_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_emp_address, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendance_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendance_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_emp_idActionPerformed

    private void attend_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attend_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)attend_table.getModel();
        add_emp_name.setText(tblModel.getValueAt(attend_table.getSelectedRow(),1).toString());
        add_emp_id.setText(tblModel.getValueAt(attend_table.getSelectedRow(),0).toString());
        add_emp_number.setText(tblModel.getValueAt(attend_table.getSelectedRow(),2).toString());
        add_emp_address.setText(tblModel.getValueAt(attend_table.getSelectedRow(),3).toString());
    }//GEN-LAST:event_attend_tableMouseClicked

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        // TODO add your handling code here:
        if(add_emp_name.getText().equals("") || add_emp_id.getText().equals("") || add_emp_number.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please, Add all the data!");
        }
        else{
            try {
                PreparedStatement stm = con.prepareStatement("insert into employee (employee_name,employee_id, employee_num, employee_address) values (?, ?, ?, ?)");
                stm.setString(1, add_emp_name.getText());
                stm.setInt(2, (int) Double.parseDouble(add_emp_id.getText()));
                stm.setInt(3, (int) Double.parseDouble(add_emp_number.getText()));
                stm.setString(4, add_emp_address.getText());
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this,"Added Successfully!");
                fillTable();
                add_emp_id.setText("");
                add_emp_name.setText("");
                add_emp_number.setText("");
                add_emp_address.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(new_emp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addDataActionPerformed

    private void updateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)attend_table.getModel();
        if(attend_table.getSelectedRowCount() == 1){
            //set to uptade value in row
            try {
                // if row selected
                int id = (int) tblModel.getValueAt(attend_table.getSelectedRow(),0);
                PreparedStatement stm = con.prepareStatement("update employee set employee_name=?, employee_num=?, employee_address=?, employee_id=? where employee_id=?");
                stm.setString(1, add_emp_name.getText());
                stm.setInt(2, (int) Double.parseDouble(add_emp_number.getText()));
                stm.setString(3, add_emp_address.getText());
                stm.setInt(4, (int) Double.parseDouble(add_emp_id.getText()));
                stm.setInt(5, id);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data Updated Successfully!");
                fillTable();
                add_emp_id.setText("");
                add_emp_name.setText("");
                add_emp_number.setText("");
                add_emp_address.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(company.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            if(attend_table.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                //if row nt selected || multi roe selected
                JOptionPane.showMessageDialog(this,"Please, Select Single Row For Update");
            }
        }
    }//GEN-LAST:event_updateDataActionPerformed

    private void deletDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletDataActionPerformed
        // TODO add your handling code here:
        // get table
        DefaultTableModel tblModel = (DefaultTableModel)attend_table.getModel();
        // delet row
        if(attend_table.getSelectedRowCount() == 1){
            try {
                //if single row selected
                int id = (int) tblModel.getValueAt(attend_table.getSelectedRow(),0);
                PreparedStatement stm = con.prepareStatement("delete from employee where employee_id=?");
                stm.setInt(1, id);
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data Deleted Successfully!");
                fillTable();
                add_emp_id.setText("");
                add_emp_name.setText("");
                add_emp_number.setText("");
                add_emp_address.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(new_emp.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else{
            //if row empty
            if(attend_table.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else{
                //if row nt selected || multi roe selected
                JOptionPane.showMessageDialog(this,"Please, Select Single Row For Update");
            }
        }
    }//GEN-LAST:event_deletDataActionPerformed

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new attend().setVisible(true);
    }//GEN-LAST:event_back_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addData;
    private javax.swing.JTextField add_emp_address;
    private javax.swing.JTextField add_emp_id;
    private javax.swing.JTextField add_emp_name;
    private javax.swing.JTextField add_emp_number;
    private javax.swing.JTable attend_table;
    private javax.swing.JPanel attendance_pnl;
    private javax.swing.JLabel back_btn;
    private javax.swing.JToggleButton deletData;
    private javax.swing.JLabel emp_id_lbl;
    private javax.swing.JLabel emp_job_lbl;
    private javax.swing.JLabel emp_job_lbl1;
    private javax.swing.JLabel emp_name_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton updateData;
    // End of variables declaration//GEN-END:variables
}
